== GitHub Explore

This repository houses all of the community-curated content for GitHub
Topics and Collections.

https://help.github.com/articles/about-topics/[Topics] help you explore
repositories in a particular subject area, learn more about that
subject, and find projects to contribute to.

https://github.com/collections[Collections] help you discover
hand-picked repositories, developers, organizations, videos, and
articles that share a common theme.

If you want to suggest edits to an existing Topic page or Collection, or
curate a new one, read our link:CONTRIBUTING.md[contributing guide] to
get started.

=== Running tests

There are some lint tests in place to ensure each Topic is formatted in
the way we expect. GitHub Actions will run the tests automatically. If
you want to run the tests yourself locally, you will need Ruby and
Bundler installed.

You can run the tests using:

[source,bash]
----
bundle install
bundle exec rubocop
----

=== Licenses

Content is released under
https://creativecommons.org/licenses/by/4.0/[CC-BY-4.0] which gives you
permission to use content for almost any purpose (but does not grant you
any trademark permissions). See link:notices.md[notices] for complete
details, including attribution guidelines, contribution terms, and
software and third-party licenses and permissions.
